# Generated by Django 4.0.6 on 2022-08-23 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='course_name', max_length=50)),
                ('branch_name', models.CharField(help_text='branch_name', max_length=50)),
            ],
            options={
                'db_table': 'course_details',
            },
        ),
        migrations.CreateModel(
            name='AddSubjectModel',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(help_text='course_name', max_length=50, null=True)),
                ('branch_name', models.CharField(help_text='branch_name', max_length=50, null=True)),
                ('subject_name', models.CharField(help_text='subject_name', max_length=50)),
                ('shortcut_name', models.CharField(help_text='shortcut_name', max_length=50)),
                ('code', models.CharField(help_text='code', max_length=50)),
            ],
            options={
                'db_table': 'subject_details',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementModel',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='title', max_length=20)),
                ('describe', models.CharField(help_text='describe', max_length=50)),
                ('date', models.DateField(help_text='date', null=True)),
            ],
            options={
                'db_table': 'announcement_details',
            },
        ),
        migrations.CreateModel(
            name='TeacherRegistrationModel',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(help_text='teacher_name', max_length=30)),
                ('gender', models.CharField(help_text='gender', max_length=10)),
                ('email', models.CharField(help_text='email', max_length=30)),
                ('mobileno', models.BigIntegerField(help_text='mobileno', null=True)),
                ('subject', models.CharField(help_text='subject', max_length=80)),
                ('password', models.CharField(help_text='password', max_length=18, null=True)),
                ('tphoto', models.ImageField(blank=True, null=True, upload_to='')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addcoursemodel')),
            ],
            options={
                'db_table': 'teacher_details',
            },
        ),
    ]
