# Generated by Django 4.0.6 on 2022-08-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcementmodel',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
