# Generated by Django 4.0.6 on 2022-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_announcementmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherregistrationmodel',
            name='teacher_otp',
            field=models.CharField(help_text='teacher_otp', max_length=18, null=True),
        ),
    ]
