# Generated by Django 4.0.6 on 2022-08-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacherapp', '__first__'),
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_SubmitModel',
            fields=[
                ('submit_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='text', max_length=80)),
                ('myfile', models.FileField(null=True, upload_to='documents/')),
                ('submited_date', models.DateField(auto_now_add=True, null=True)),
                ('assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherapp.addassignmentmodel')),
            ],
            options={
                'db_table': 'assignmentsubmit_detail',
            },
        ),
        migrations.CreateModel(
            name='StudentRegisterModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(help_text='student_name', max_length=50)),
                ('student_rollno', models.CharField(help_text='student_rollno', max_length=20)),
                ('student_mobileno', models.BigIntegerField(help_text='student_mobileno', null=True)),
                ('student_email', models.CharField(help_text='student_email', max_length=30)),
                ('student_password', models.CharField(help_text='student_password', max_length=18)),
                ('student_photo', models.FileField(null=True, upload_to='documents/')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addcoursemodel')),
            ],
            options={
                'db_table': 'student_detail',
            },
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('remarks', models.CharField(help_text='remarks', max_length=20)),
                ('marks', models.IntegerField(help_text='marks')),
                ('stu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.assignment_submitmodel')),
            ],
            options={
                'db_table': 'teacher_result',
            },
        ),
        migrations.AddField(
            model_name='assignment_submitmodel',
            name='submited_student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentapp.studentregistermodel'),
        ),
    ]
