# Generated by Django 4.0.6 on 2022-08-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_remove_resultmodel_result_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_submitmodel',
            name='submit_status',
            field=models.CharField(default='pending', help_text='submit_status', max_length=20),
        ),
    ]
