# Generated by Django 4.0.6 on 2022-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_assignment_submitmodel_submit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistermodel',
            name='student_otp',
            field=models.CharField(help_text='student_otp', max_length=18, null=True),
        ),
    ]
