# Generated by Django 4.0.6 on 2022-08-23 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddAssignmentModel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject', models.CharField(help_text='subject', max_length=50)),
                ('assignment_title', models.CharField(help_text='assignment_title', max_length=40)),
                ('assignment_description', models.CharField(help_text='assignment_description', max_length=50)),
                ('posting_date', models.DateField(auto_now_add=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('assignment_marks', models.IntegerField(help_text='assignment_marks')),
                ('assignment_file', models.FileField(null=True, upload_to='documents/')),
                ('Assignment_details', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.teacherregistrationmodel')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.addcoursemodel')),
            ],
            options={
                'db_table': 'assignment_details',
            },
        ),
    ]
