# Generated by Django 4.0.6 on 2022-08-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addassignmentmodel',
            name='accept',
            field=models.CharField(help_text='accept', max_length=40, null=True),
        ),
    ]
