# Generated by Django 4.0.6 on 2022-08-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherapp', '0002_addassignmentmodel_accept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addassignmentmodel',
            name='accept',
        ),
    ]
